version: "3"
services:
  web:
    build: ./dash_app
    ports:
      - "127.0.0.1:8050:8050"
    volumes:
      - "user_data:/app/user_data"
    environment:
      SECRET_KEY: "${SECRET_KEY:?missing_secret_key}"

  redis:
    build: ./redis
    volumes:
      - "redis_data:/data"

  worker:
    build: ./worker
    volumes:
      - "user_data:/app/user_data"
    environment:
      REDIS_HOST: "redis"


volumes:
  user_data:
  redis_data:


# export SYSTEM_VERSION_COMPAT=1