version: "3.9"
services:
  web:
    build: ./dash_app
    ports:
      - "8050:8050"
    environment:
      # Generate by running python3 -c "print(__import__('secrets').token_hex(24))"
      SECRET_KEY: "SECRET_KEY_CHANGE_ME"
    volumes:
      - "./user_storage:/app/user_data"

  # redis:
  #   image: "redis:alpine"