version: "3"
services:
  web:
    build: ./dash_app
    ports:
      - "127.0.0.1:8050:8050"
    restart: unless-stopped
    volumes:
      - "user_data:/app/user_data"
    environment:
      SECRET_KEY: "${SECRET_KEY:?missing_secret_key}"

  redis:
    build: ./redis
    restart: unless-stopped
    volumes:
      - "redis_data:/data"

  worker:
    build: ./worker
    restart: unless-stopped
    volumes:
      - "user_data:/app/user_data"
      - "/home/ilnitsky/nr:/blast/blastdb"
      - "/usr/lib/ncbi-blast+/:/blast/lib/:ro"
      - "/lib/x86_64-linux-gnu/:/blast/lib2/:ro"
      - "/lib64/:/blast/lib3/:ro"
      - "/usr/bin/blastp:/blast/bin/blastp:ro"
    environment:
      REDIS_HOST: "redis"
      LD_LIBRARY_PATH: "/blast/lib/:/blast/lib2/:/blast/lib3"


volumes:
  user_data:
  redis_data: