version: "3"
services:
  web:
    build:
      context: ./dash_app
      args:
        DEBUG: "1"
    restart: unless-stopped
    ports:
      - "8050:8050"
    environment:
      # Generate by running python3 -c "print(__import__('secrets').token_hex(24))"
      SECRET_KEY: "SECRET_KEY_CHANGE_ME"
      PYTHONUNBUFFERED: "1"
    volumes:
      - "user_data:/app/user_data"

  redis:
    build: ./redis
    restart: unless-stopped
    volumes:
      - "redis_data:/data"

  worker:
    build:
      context: ./worker
      args:
        DEBUG: "1"
    restart: unless-stopped
    volumes:
      - "user_data:/app/user_data"
      - "./blast_data:/blast/blastdb"
    environment:
      REDIS_HOST: "redis"
      PYTHONUNBUFFERED: "TRUE"

volumes:
  user_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ./user_data
  redis_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ./redis_data



# export SYSTEM_VERSION_COMPAT=1